tailflow/laravel-orion

.github/workflows/ci.yml
src/Drivers/Standard/QueryBuilder.php
tests/Feature/StandardIndexFilteringOperationsTest.php

When two fields with the same name were used from both main and relation resources in filters, search, or sorting, it resulted in ambiguous column sql exception.

fix: ambiguous column sql exception

---

.github/workflows/ci.yml
src/Concerns/HandlesRelationStandardBatchOperations.php
src/Concerns/HandlesRelationStandardOperations.php
src/Concerns/HandlesStandardBatchOperations.php
src/Concerns/HandlesStandardOperations.php

Laravel Model's `fill` method already checks and fills keys by the `fillable` and `guarded` attributes.
Hence there is no need to retrieve only `fillable` attributes from the `request` bag, we can let the framework handle it for us.
All tests are passing.
Closes #18

Remove unnecessary Request fill check

---

src/Concerns/HandlesRelationStandardOperations.php
src/Http/Middleware/EnforceExpectsJson.php
tests/Unit/Http/Middleware/EnforceExpectsJsonTest.php

I´m having troubles with content negotiation because the original 'Accept' header is lost.
In some routes, I send back different content depending on the 'Accept' header. For example when receiving requests with `application/spec1+json`.
But, because this header is always changed to 'application/json', content negotiation is impossible.
Replace EnforceExpectsJson@handle:
```php
$request->headers->add(['Accept' => 'application/json']);
```
With:
```php
if (!$request->expectsJson()) {
$request->headers->add(['Accept' => 'application/json,' . $request->header('Accept')]);
}
```
Prepending the mime type on the beginning, so methods like `$request->expectsJson()` will still working.

Prepends 'application/json' to 'Accept' header

---

src/Concerns/HandlesRelationStandardOperations.php

Hi,
I have the following situation: 
Model **Document** --> 1:1 --> Model **File** --> 1:1 --> Model **FileContent**. 
My model definition of my **Document** looks like
```php
public function file(): HasOne
{
return $this->hasOne(File::class);
}
public function filecontent(): HasOneThrough
{
return $this->hasOneThrough(Filecontent::class, File::class);
}
```
I declared the following routes (routes/api.php):
- Orion::resource('documents', DocumentController::class)
- Orion::hasOneResource('documents', 'file', FileController::class)
- Orion::hasOneThroughResource('documents', 'filecontent', FilecontentController::class)
These declarations result in the following routes:
```
| POST      | api/documents/{document}/file
| DELETE    | api/documents/{document}/file/{file?}
| PUT|PATCH | …
```

HandlesRelationStandardOperations->isOneToOneRelation seems to ignore HasOneThrough

---

src/Concerns/HandlesRelationManyToManyOperations.php
src/Concerns/HandlesRelationOneToManyOperations.php
src/Concerns/HandlesRelationStandardBatchOperations.php
src/Concerns/HandlesRelationStandardOperations.php

This change allows for model policies to also check the parent model for authorization
Below is an example of what is possible with this change.
```php
class PostPolicy {
public function update($user, $team)
{
return $team->user_id === $user->id;
}
}
class PostMetaPolicy {
public function update($user, $postMeta, $post)
{
return Gate::forUser($user)->inspect('update', $post);
}
public function create($user, $post)
{
return Gate::forUser($user)->inspect('update', $post);
}
}
```
This is completely backwards compatible and lets the user decide if he wants to check the parent relation.

Add parent entity to the model policy where possible

---

src/Http/Requests/Request.php

Hi @alexzarbn,
In my project it is necessary that I can define validation messages concretely for each endpoint (store, update, etc.). I tried to implement this and would be happy if my changes would find their way into one of the next releases.

Added possibility to customize validation messages for the concrete endpoint

---

src/Concerns/HandlesStandardBatchOperations.php
src/Concerns/HandlesStandardOperations.php

Hi @alexzarbn,
during development of my API it was sensefull to have a hook before freshening the entity. It would be nice of you if you have an eye on this and maybe merge it.

Hook before freshening the entity

---

src/Facades/Orion.php

This PR add's the `@method` and `@see` doc blocks to the `Orion` facade class, for better IDE development usage (auto complete etc.)

Add facade docs

---

src/Facades/Orion.php

This PR fixes an IDE bug introduced by #141 whereby IDE's such as PHPStorm complain about calling the Facade methods statically.

Fix IDE static method call error

---

composer.json
src/Drivers/Standard/ParamsValidator.php
src/Drivers/Standard/QueryBuilder.php
src/Specs/Builders/Partials/RequestBody/Search/FiltersBuilder.php
tests/Feature/StandardIndexFilteringOperationsTest.php

In order to be compliant with Laravel query builder `where` method, this PR makes operator field optional in filters.
Default value is `=`.
PS i added `laravel/legacy-factories` in dev dependecies in order to make this package testable on new Laravel version

Make operator optional in filters

---

composer.json

If a certain project already had `orchestra/testbench` package v7.0 or above installed, this package cannot be installed because `symfony/yaml` package v6.0 or above is in the lock file. I have also tried `composer require tailflow/laravel-orion -W` and does not work. This PR fixes that problem.

chore: allow higher version of `symfony/yaml` dependency

---

config/orion.php
src/Specs/Builders/TagsBuilder.php

Motivation:
Sometimes we need to add extra tags to the specs but the merge of this tag property doesn't work very well.
Some documentation tools like redoc use these tags to add sections to the documentation. Something like that:

Add default tags config

---

composer.json
config/orion.php
src/Drivers/Standard/ParamsValidator.php
src/Drivers/Standard/QueryBuilder.php
src/Specs/Builders/Partials/RequestBody/Search/FiltersBuilder.php
tests/Feature/StandardIndexNestedFilteringOperationsTest.php
tests/Fixtures/app/Providers/OrionServiceProvider.php

Hello there,
We are having some trouble using orion because you basically can't handle priority on "or" and "and" on sql queries. This is problematic for us and we really need this to avoid custom routes on our project.
Here is my proposition for adding nested filters.
**What does it do ?**
This PR allows to add nested filters infinitely. Example of a search query:
```json
{
"filters": [
{"field": "is_for_all", "value": "true"},
{
"value": [
{"field": "started_at", "operator": ">=", "value": "2022-05-23"},
{"field": "ended_at", "operator": "<=", "value": "2022-06-23", "type": "or"}
],
"type": "or"
}
]
}
```
Your plugin is really well developed, it was really easy to implement.
**QUESTIONS:**
Do you have any idea how we could validate infinite arrays ? I basically removed requirement on …

:sparkles: nested filters

---

src/Drivers/Standard/ParamsValidator.php

After the release of nested filters I got this error:
```
Undefined array key "filters"
```
This PR fixes it.

fixes Undefined array key "filters" error

---

config/orion.php
src/Concerns/HandlesRelationManyToManyOperations.php
src/Concerns/HandlesRelationStandardBatchOperations.php
src/Concerns/HandlesRelationStandardOperations.php
src/Concerns/HandlesStandardBatchOperations.php
src/Concerns/HandlesStandardOperations.php

Laravel has a cool method "validated" on Request. This method returns only the validated data, filtering out any properties not defined on the validation rules. It has a similar effect to the model's fillable property but also applies to data inside arrays.
```php
$fillable = ['name', 'address'];
$rules = [
'name' => 'string',
'address' => 'array',
'address.city' => 'string'
];
$data = [
'name' => 'Ricardo',
'address' => [
'city' => 'Curitiba',
'country' => 'Brazil',
],
'phone' => '+5511999999999',
];
$model->fill($request->all());
// model is ['name' => ..., 'address' => ['city' => ..., 'country' => ...]]
// phone is filtered by "fillable", country is not filtered
$model->fill($request->validated());
// model is ['name' => ..., 'address' => ['city' => ...]]
// both phone and country are …
```

Use validated() instead of all() for resources data

---

src/ValueObjects/Specs/Responses/Success/EntityResponse.php

JsonResource has a property named "wrap" which defines how data should be wrapped in a response. The default value is "data" which makes the response look like this:
```php
$resource->toResponse();
/*
[
'data' => [
'id' => 1,
'name' => 'Test',
// ...
]
]
*/
```
The wrapping property can be changed to any value or disabled by calling `JsonResource::withoutWrapping();`. This is particularly useful, making the response return the resource directly. [Reference docs](https://laravel.com/docs/9.x/eloquent-resources#data-wrapping)
```php
$resource->toResponse();
/*
[
'id' => 1,
'name' => 'Test',
// ...
]
*/
```
The current implementation of the specs generation doesn't consider the wrap configuration and wraps resources always within "data".
This PR fixes that, generating the correct specs with …

[Fix] Consider JsonResource wrapping to generate specs

---

src/ValueObjects/Specs/Requests/Batch/BatchUpdateRequest.php

The documentation states the following regarding batchUpdate parameters:
> The endpoint expects an object in request payload with resources **object**, where each key is a resource id and item is an object representing a resource (e.g. a post) to update.
The current implementation generates an spec with the resources param defined as an **array** of resources.
This PR fixes the spec generator, making it compliant with the documentation.
This is not the perfect description of the request, but at least the type is correct.

[Fix] Fixes batchUpdate spec

---

src/Specs/Builders/PathsBuilder.php

The order in which the operations are described in the generated OpenApi specification is not defined and not very intuitive.
For instance, the retrieve operations are scattered among other operations. We have **`search`**, followed by `batch operations`, then back to **`index`**, then `create`, then back **`get`**.
This PR improves this by sorting the operations and grouping them together in the following order: Create, Retrieve, Update, Delete, Batch CRUD, and so on.

[Improvement] Reorder the operations during spec generation

---

src/Specs/Managers/SchemaManager.php
src/ValueObjects/Specs/Schema/Properties/AnySchemaProperty.php
src/ValueObjects/Specs/Schema/Properties/ArraySchemaProperty.php
src/ValueObjects/Specs/Schema/Properties/BinarySchemaProperty.php
src/ValueObjects/Specs/Schema/Properties/DateSchemaProperty.php
src/ValueObjects/Specs/Schema/Properties/ObjectSchemaProperty.php
src/ValueObjects/Specs/Schema/SchemaProperty.php

The DBAL library defines many default types, but only a few of those are currently implemented in Orion. Useful types like JSON, Array and Object are missing. Besides that, the current default type is "string". By adding a AnySchemaProperty and using it as default we can have better typings for our OpenApi specs.
This PR implements type resolution for all DBAL defined types and introduces an "any" type.

Improves type resolution for all DBAL types

---

src/Specs/Builders/PathsBuilder.php

Sometimes we need more flexibility to build paths. In this case, we need a way to extend that object value. The laravel dependencies injections can be used to give that flexibility.  I need to add more properties to mine specs. But the current implementation uses `new` to instantiate the Path. 
` $this->app->bind(SpecsPath::class, fn ($app, $params) => new Path($params['path']));`

Add app make to resolve Path objectValue

---

src/Http/Controllers/BaseController.php

updated the function to respect the `paginationDisabled` property and its value if it exists. right now it only checks if it exists.

Update shouldPaginate function in BaseController

---

src/Specs/Builders/TagsBuilder.php

By this, I hope to be able to use config to describe the tags for my API docs page renderer, since it uses the last instance of the defined tag by default (which always ends up being this dummy description).
Also, by all means, if I'm out of place here, show me what I should do instead! 😅 I hope I'm not causing a problem with this.

Only add tags that are missing from config

---

src/Http/Routing/PendingResourceRegistration.php
tests/Unit/OrionTest.php

This PR introduces a new method called `withoutSearch()` which is similar to the `withoutBatch()` method and removes the `search` endpoint from the resource declaration.
I know its pretty easy to do `->except('search')`, but this overwrites the default `except` values, so you have to do `->except(['search', 'restore'])` at the least.
I added tests to cover this and I didn't find any for the `withoutBatch()`, so I included them as well.
Let me know if I should do anything else in this PR. Thanks

Add routing method to remove search route

---

src/Drivers/Standard/QueryBuilder.php
tests/Fixtures/app/Models/Post.php
tests/Unit/Drivers/Standard/QueryBuilderTest.php

This PR is directly related to #256. Due to `applyIncludesToQuery` being after any of the filtering/scoping for a search endpoint, if your scope eager loads any of the same relationships as in the `include` parameter, the scope is overwritten and thus no longer applies. This PR simply reorders the query modifiers so that your explicit scope declarations will always take precedence.
Endpoint: /api/tasks/search?include=users
Scope:
```
public function scopeSomething(Builder $query): void
{
$query->with(['users' => fn($query) => do something ]);
}
```
Scope would not be applied since the include is also eager loading the relationship and would take precedence.

Prevent query builder from overwriting scopes

---

src/Specs/Builders/PropertyBuilder.php
tests/Unit/Specs/Builders/PropertyBuilderTest.php

Fixed issue where the specs incorrectly marked a field as non-nullable. The issue was introduced when it was an object with getNotNull function then was changed to an array with a nullable property. 
Issue reference: https://github.com/tailflow/laravel-orion/commit/e3e5b657f280901bb1d76892d5ffbcd2df3e3347#diff-1d3d225dd65e11ca23b0f59cc7f32929e6421b4bcbfe6be3ce3e67b958640a86R22

Fix - Specs property nullable issue which was reversed in PropertyBuilder
